import { useState } from 'react';
import type { AnalysisResult } from '../../engine/types';

interface DownloadPDFButtonProps {
  result: AnalysisResult;
}

function buildReportHTML(result: AnalysisResult): string {
  const date = new Date(result.analyzedAt).toLocaleString();
  const signals = result.signals || [];
  const suspiciousSpans = result.suspiciousSpans || [];

  const signalsHtml = signals.map(s => `
    <div style="margin-bottom:12px;padding:8px 12px;background:#f9fafb;border-radius:8px">
      <div style="display:flex;justify-content:space-between;margin-bottom:4px">
        <span style="font-weight:500;font-size:14px;color:#374151">${s.name}</span>
        <span style="font-weight:600;font-size:14px;color:${s.score >= 60 ? '#16a34a' : '#d97706'}">${Math.round(s.score)}%</span>
      </div>
      <div style="height:6px;background:#e5e7eb;border-radius:3px;margin-bottom:4px;overflow:hidden">
        <div style="height:100%;width:${s.score}%;background:${s.score >= 60 ? '#22c55e' : '#f59e0b'};border-radius:3px"></div>
      </div>
      <p style="font-size:12px;color:#6b7280;margin:0">${s.details}</p>
    </div>
  `).join('');

  const suspiciousHtml = suspiciousSpans.length > 0 ? `
    <div style="margin-top:24px;padding:12px;background:#fef2f2;border-radius:8px;border:1px solid #fecaca">
      <h3 style="font-size:14px;font-weight:600;color:#991b1b;margin:0 0 8px">
        ${suspiciousSpans.length} Suspicious Pattern${suspiciousSpans.length > 1 ? 's' : ''} Detected
      </h3>
      ${suspiciousSpans.slice(0, 10).map(span => `
        <div style="font-size:12px;color:#7f1d1d;margin-bottom:4px">
          <strong>"${span.text.slice(0, 60)}"</strong> — ${span.reason}
        </div>
      `).join('')}
    </div>
  ` : '';

  const text = result.originalText.length > 2000
    ? result.originalText.slice(0, 2000) + '...'
    : result.originalText;

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>TruthScope Report</title>
<style>
  body { font-family: system-ui, sans-serif; margin: 0; padding: 32px; color: #111827; }
  * { box-sizing: border-box; }
</style></head><body>
  <div style="border-bottom:2px solid #e5e7eb;padding-bottom:16px;margin-bottom:24px">
    <h1 style="font-size:28px;font-weight:700;margin:0">TruthScope Report</h1>
    <p style="font-size:12px;color:#6b7280;margin:4px 0 0">Generated: ${date}</p>
    <p style="font-size:12px;color:#6b7280;margin:4px 0 0">Intent: ${result.intent.label}</p>
  </div>
  ${result.overallScore !== undefined ? `
  <div style="margin-bottom:24px">
    <div style="font-size:14px;color:#6b7280;margin-bottom:4px">Overall Credibility Score</div>
    <div style="font-size:48px;font-weight:700">${result.overallScore}/100</div>
    ${result.verdict ? `<div style="font-size:16px;color:#6b7280;margin-top:4px">${result.verdict.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())}</div>` : ''}
  </div>` : ''}
  ${signals.length > 0 ? `<div style="margin-bottom:24px"><h2 style="font-size:16px;font-weight:600;margin-bottom:12px">Signal Analysis</h2>${signalsHtml}</div>` : ''}
  <div><h2 style="font-size:16px;font-weight:600;margin-bottom:12px">Analyzed Text</h2>
    <p style="font-size:13px;line-height:1.6;white-space:pre-wrap">${text.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</p>
  </div>
  ${suspiciousHtml}
  <div style="margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:11px;color:#9ca3af;text-align:center">
    Generated by TruthScope — All analysis performed locally in-browser.
    This is a screening tool, not a definitive truth oracle.
  </div>
</body></html>`;
}

export function DownloadPDFButton({ result }: DownloadPDFButtonProps) {
  const [generating, setGenerating] = useState(false);

  const handleDownload = async () => {
    setGenerating(true);
    try {
      const [{ jsPDF }] = await Promise.all([import('jspdf')]);

      const html = buildReportHTML(result);
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();

      await pdf.html(html, {
        x: 10, y: 10, width: pdfWidth - 20,
        windowWidth: 800, autoPaging: 'text',
        margin: [10, 10, 10, 10],
      });

      pdf.save(`TruthScope-Report-${Date.now()}.pdf`);
    } catch (err) {
      console.error('PDF generation failed:', err);
      alert('Failed to generate PDF. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <button
      onClick={handleDownload}
      disabled={generating}
      className="flex items-center gap-2 px-5 py-2.5 bg-gray-900 text-white rounded-lg font-medium hover:bg-gray-800 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors"
    >
      {generating ? (
        <>
          <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
          Generating...
        </>
      ) : (
        <>
          <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          Download PDF Report
        </>
      )}
    </button>
  );
}
